modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mixins]]
config = [
    "candlelight-common.mixins.json",
    "candlelight.mixins.json"
]

[[mods]]
modId = "candlelight"
version = "${version}"
displayName = "[Let's Do] Candlelight"
authors = "satisfy"
description = '''
Ever dreamed of the perfect dinner? Prepare mouth-watering meals, transform your dining space into a masterpiece, and create unforgettable dining experiences!
'''
logoFile = "pack.png"

[[dependencies.candlelight]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.candlelight]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.candlelight]]
modId = "farm_and_charm"
mandatory = true
versionRange = "[0.0.1,)"
ordering = "AFTER"
side = "BOTH"